sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
script:
  - npm run verify
after_success:
  - npm run report-coverage
  - npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
addons:
  browserstack:
    username: jan.molak@smartcodeltd.co.uk
    access_key:
      secure: wW/joCUvC0DyVQfpp40ExJtxJCyuEyzY2+LqmdzJIDKOO+DtbsBCLgrCjseq+tb3kMNC6VcpoD/iIqjK3NHP19lgnPEEZeXdHvK5RhGp4GzzXMbbEHNmT+yfwPMCBH8qG7zNg6wmlfA4N9j8OnC4EHCcIk9+E5++uKp1/kakhqmZ6IJORNgnl2ZT+Fn7nYat0VLyh7GtDAeiJSfD0lFYrqkt0VIEbEmPlnk8viOT2ci/uQXvoSG8Hj4y2vA2ieA2JGJ0mmhvhM0iGjUYloCeBAz2Q19VgOi+RXZDdiTJqmuBFKuAHhi0EJoHLr6QdUE+XhKnBxIAEpm/uM166V/qj20Rd5QBIlCg7xSknceynxWmuZqJaXDPE5yoMcqnAZ1V/TC0PJDQxdxSEhflVAC2HXXBuD5UibKFqN0GXOOENSuinFFCf1OahxR6odaY81V+S6qOUrXWENmWd34I88z9DrEbrvYYIK5B6xTe8yJlGiTrCbOIiy7RiElqbM7JdfgLQ4ixbC+GyUrGVR9LFaoPca8Mmgp/+tHtpQZTQkWlbQMK6aLN0QO178c9AA6dhSOMes0fSqIuvTyoY6YdfXOEoI4jG0i/Vre+dnVLUsjbWx039+rwQSvQprT4h4JtYQLOmLAvD4R18TuBVbCYKGKfukNv5P4ZrHIxOd2gQBfzMvo=
env:
  global:
  - BROWSERSTACK_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BROWSERSTACK_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  - secure: "PcVAVdrUj1z7fztYklzExbkxCkwEgdKaaSt4eQNNuxdBvj8MwDAp7JvKasqAALBLJgcthj+jt+BU2l3LABPZyZPkl6A6FstoXvmK0fUAPr2k9InuiFX6UgybNKvhIQOyF++9bw0kCTZlkGn3KSw0vLZAx10/+XCb8mu7ghwylrI="
  - secure: "IO5ls6xcCpbgxEJFpKJhh5WT1FxwZOiwdhXs2OMElPCDAoMrQcooClvlSG6MWAY344F9p6jS3JFy0m8AZWw9IuJr5HeS36o5HS1Zf1+A/Awe8BDkyfHZTORZPU6VucFfLmZxgDXSFAmKxTaXUPhPQGXGbXuvT8KdkbqT43eA2HI="
