check-leaks: false
color: true
diff: true
full-trace: true
reporter: '@serenity-js/mocha'
reporter-options:
  - 'specDirectory=test/spec'
require:
  - ts-node/register
  - test/support/setup.ts
timeout: 5000
v8-stack-trace-limit: 100
