check-leaks: false
color: true
diff: true
full-trace: true
reporter: '../../packages/mocha'
require:
  - 'ts-node/register'
  - 'src/serenity.config.ts'
timeout: 30000
v8-stack-trace-limit: 100
spec:
  - './node_modules/@integration/web-specs/spec/**/*.spec.ts'
