check-leaks: false
color: true
diff: true
full-trace: true
reporter: '../../packages/mocha'
require:
  - 'ts-node/register'
  - 'src/serenity.config.ts'
timeout: 30000
v8-stack-trace-limit: 100
spec:
# DONE
  - './node_modules/@integration/web-specs/spec/expectations/isClickable.spec.ts'
  - './node_modules/@integration/web-specs/spec/expectations/isEnabled.spec.ts'
  - './node_modules/@integration/web-specs/spec/expectations/isPresent.spec.ts'
  - './node_modules/@integration/web-specs/spec/expectations/isActive.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/execute-script/ExecuteAsynchronousScript.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/execute-script/ExecuteScriptFromUrl.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/execute-script/ExecuteSynchronousScript.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/Clear.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/Click.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/DoubleClick.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/Enter.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/Hover.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/Navigate.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/Press.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/RightClick.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/Scroll.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/TakeScreenshot.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/interactions/Wait.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/models/PageElement.located.*.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/models/Cookie.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/models/Page.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/models/PageElement.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/models/PageElements.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/models/PageElements.located.*.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/models/PageElements.patterns.spec.ts'
  - './node_modules/@integration/web-specs/spec/screenplay/questions/*.spec.ts'
  - './node_modules/@integration/web-specs/spec/stage/**/*.spec.ts'

# WIP

# TODO
#  - './node_modules/@integration/web-specs/spec/screenplay/interactions/Select.spec.ts'    # todo  PageElement.selectOptionByValue() PageElement.selectOptionByLabel()
#  - './node_modules/@integration/web-specs/spec/expectations/isSelected.spec.ts'
#  - './node_modules/@integration/web-specs/spec/expectations/isVisible.spec.ts'
#  - './node_modules/@integration/web-specs/spec/screenplay/models/ModalDialog.spec.ts'
