blank_issues_enabled: true
contact_links:
  - name: Serenity/JS Community Chat
    url: https://matrix.to/#/#serenity-js:gitter.im
    about: "Ask and answer questions about Serenity/JS and become part of our Community!"
