name: Feature Request
description: Suggest an idea for Serenity/JS
title: "Serenity/JS should ..."
body:

  - type: markdown
    attributes:
      value: |
        👋 Hello! Thanks for proposing an enhancement to Serenity/JS! Tell us more about your idea.

  - type: textarea
    id: problem
    attributes:
      label: What's the problem you're trying to solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: How would you like to solve it?
      description: |
        What's your preferred solution, and why is it the best way to do it?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Are there any alternatives?
      description: |
        Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: How can we make it happen?
      description: |
        We'll need someone to help make your idea happen.
        
        I would like to:
      options:
        - label: "[work on this myself](https://serenity-js.org/contributing/#propose-an-enhancement) (with Serenity/JS team guidance)"
        - label: "[hire the Serenity/JS team](https://github.com/sponsors/serenity-js) to build it for me"
        - label: "add it to the Serenity/JS backlog and wait for a volunteer"
