version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    target_branch: "2.0"
    version_requirement_updates: "auto"
    ignored_updates:
      - match:
          dependency_name: "cucumber"
