name: Release Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:

  lint:
    if:       "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Node Modules (all)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Lint
        run: make lint

  compile:
    if:       "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Node Modules (@integration)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Compile
        run: make compile

      - name: Compress Libs
        run:  7z a compiled-libs.zip package.json "integration/*/lib/*" "integration-web/*/lib/*" "packages/*/lib/*"
      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: compiled-libs
          path: |
            compiled-libs.zip

  test-linux-node-lts-active:
    name: test-linux-node-lts-active (14.x)
    needs:
      - compile
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Node Modules (@serenity-js)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP=@serenity-js install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z x -aoa compiled-libs.zip
      # todo: Enable when the tests are ready to run on SauceLabs
      #      - name: Open Sauce Connect Tunnel
      #        uses: saucelabs/sauce-connect-action@v1
      #        with:
      #          username: ${{ secrets.SAUCE_USERNAME }}
      #          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
      #          tunnelIdentifier: github-serenity-js-test-linux-node-14.x-tunnel

      - name: Test
        run: make test
      # todo: Enable when the tests are ready to run on SauceLabs
      #        env:
      #          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      #          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: test-reports
          path: |
            target/**/*
            package.json

  test-linux-node-lts-other:
    needs:
      - compile
    runs-on:  ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 16.x ]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Modules (@serenity-js)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP=@serenity-js install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z x -aoa compiled-libs.zip

      - name: Test
        run: make test

  test-windows-node-lts:
    needs:
      - compile
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x ]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Node Modules (@serenity-js)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP=@serenity-js install
        env:
          CHROMEDRIVER_FILEPATH: "C:\\SeleniumWebDrivers\\ChromeDriver\\chromedriver.exe"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z.exe x -aoa compiled-libs.zip
      - name: Test
        run: make test

  web-integration-test-linux-node-lts-active:
    needs:
      - compile
    runs-on:  ubuntu-latest
    steps:
      - name: Open Sauce Connect Tunnel
        uses: saucelabs/sauce-connect-action@v1
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-serenity-js-web-integration-test-linux-node-lts-active-${{ github.run_number }}-tunnel

      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Node Modules (@integration)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP=@integration install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z x -aoa compiled-libs.zip

      - name: Integration Test
        run: make integration-test-web
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_TUNNEL_ID: github-serenity-js-web-integration-test-linux-node-lts-active-${{ github.run_number }}-tunnel

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: web-integration-test-linux
          path: integration-web/web/target/

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: web-integration-test-coverage-reports
          path: |
            target/**/*
            package.json
            
  non-web-integration-test-linux-node-lts-active:
    needs:
      - compile
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Node Modules (@integration)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP=@integration install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z x -aoa compiled-libs.zip

      - name: Integration Test
        run: make integration-test-non-web

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: non-web-integration-test-coverage-reports
          path: |
            target/**/*
            package.json

  report:
    runs-on:  ubuntu-latest
    needs:
      - test-linux-node-lts-active
      - web-integration-test-linux-node-lts-active
      - non-web-integration-test-linux-node-lts-active
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Node Modules (root)
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download code coverage reports (test)
        uses: actions/download-artifact@v2
        with:
          name: test-reports

      - name: Download code coverage reports (web integration test)
        uses: actions/download-artifact@v2
        with:
          name: web-integration-test-coverage-reports
      - name: Download code coverage reports (non-web integration test)
        uses: actions/download-artifact@v2
        with:
          name: non-webintegration-test-reports

      - name: Merge code coverage reports
        run: make report

      - name: Publish coverage
        continue-on-error: true
        if: github.ref == 'refs/heads/master'
        run: npm run coverage:publish
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  release:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - lint
      - test-linux-node-lts-active
      - test-linux-node-lts-other
      - test-windows-node-lts
      - web-integration-test-linux-node-lts-active
      - non-web-integration-test-linux-node-lts-active
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-lerna
        with:
          github_token:   ${{ secrets.GITHUB_TOKEN }}
          git_user_email: ${{ secrets.RELEASE_GH_EMAIL }}
          git_username:   ${{ secrets.RELEASE_GH_USERNAME }}
          npm_token:      ${{ secrets.NPM_TOKEN }}
      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z x -aoa compiled-libs.zip
      - name: Setup Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Node Modules (root)
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Publish artifacts
        run: npm run lerna:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: changelog
          path: |
            CHANGELOG.md

  site:
    runs-on: ubuntu-latest
    needs:
      - release
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/setup-lerna
        if: github.ref == 'refs/heads/master'
        with:
          github_token:   ${{ secrets.GITHUB_TOKEN }}
          git_user_email: ${{ secrets.RELEASE_GH_EMAIL }}
          git_username:   ${{ secrets.RELEASE_GH_USERNAME }}
          npm_token:      ${{ secrets.NPM_TOKEN }}
      - name: Download changelog
        if: needs.release.result == 'success'
        uses: actions/download-artifact@v2
        with:
          name: changelog
      - name: Setup Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Node Modules (@documentation)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP=@documentation install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Build Serenity/JS website
        run: make site

      - name: Publish website
        if: github.ref == 'refs/heads/master'
        run: npm run site:publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
