name: "Chore: Delete old workflows"
on:
  schedule:
    - cron: '0 16 * * *'
# Run daily, at 16:00 on the 1st day of month.

jobs:
  delete_old_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 10
          dry_run: 'true'
