name: Local Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

jobs:

  local_build:
    if:       "!contains(github.event.head_commit.message, 'ci skip')"
    strategy:
      matrix:
        os:
          - linux-latest
          - windows-latest
          - macos-latest
      fail-fast: false
    runs-on:  ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (windows)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make install
        env:
          CHROMEDRIVER_FILEPATH: "C:\\SeleniumWebDrivers\\ChromeDriver\\chromedriver.exe"

      - name: Install Node Modules (macos, linux)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Local build
        run: make verify report site
