name: Release Pipeline

on:
  push:
    branches:
      - master

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: OleksiyRudenko/gha-git-credentials@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
      - run: npm ci
      - run: make clean
      - run: make verify
        env:
          CI: true
      - run: make report
      - run: make site
      - name: Publish coverage
        run: npm run coverage:publish
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
      - name: Publish artifacts
        run: npx lerna publish --yes
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish site
        run: npm run site:publish
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}

