name: Release Pipeline

on: [ push ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
      - run: npm ci
      - run: make clean verify report site
        env:
          CI: true
      - name: Release
        if: github.ref == 'refs/heads/master'
        run: |
          npm run coverage:publish
          npm run lerna publish --yes
          npm run site:publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}

