name: Release Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]

jobs:

  #
  # Build
  #

  lint:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

# exclude documentation
      - name: Install Node Modules (root)
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Lint
        run: make lint

  compile:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (all)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP_SCOPE=libs install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Compile
        run: make COMPILE_SCOPE=libs compile

      - name: Compress Libs
        run:  7z a compiled-libs.zip package.json "integration/*/lib/*" "packages/*/lib/*"
      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: compiled-libs
          path: |
            compiled-libs.zip

  #
  # Test
  #

  test-linux-node-lts-active:
    name: test (Linux, LTS)
    needs:
      - compile
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (@serenity-js)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP_SCOPE=@serenity-js install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z x -aoa compiled-libs.zip

      - name: Test
        run: make test

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: test-reports
          path: |
            target/**/*
            package.json

  test-linux-node-lts-previous:
    name: test (Linux, LTS-1)
    needs:
      - compile
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install Node Modules (@serenity-js)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP_SCOPE=@serenity-js install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z x -aoa compiled-libs.zip

      - name: Test
        run: make test

  test-linux-node-next:
    name: test (Linux, Next)
    needs:
      - compile
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Node Modules (@serenity-js)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP_SCOPE=@serenity-js install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z x -aoa compiled-libs.zip

      - name: Test
        run: make test

  test-windows-node-lts-active:
    name: test (Windows, LTS)
    needs:
      - compile
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (@serenity-js)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP_SCOPE=@serenity-js install
        env:
          CHROMEDRIVER_FILEPATH: "C:\\SeleniumWebDrivers\\ChromeDriver\\chromedriver.exe"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z.exe x -aoa compiled-libs.zip
      - name: Test
        run: make test

  #
  # Integration test
  #

  test-integration-saucelabs:
    name: integration (SauceLabs)
    # don't run on forks which won't have access to secrets
    if: ${{ !github.event.pull_request.head.repo.fork }}
    needs:
      - compile
    runs-on: ubuntu-latest
    steps:
      - name: Open Sauce Connect Tunnel
        uses: saucelabs/sauce-connect-action@v2
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelIdentifier: github-serenity-js-test-integration-saucelabs-${{ github.run_number }}-tunnel

      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (@integration)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP_SCOPE=@integration install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run: 7z x -aoa compiled-libs.zip

      - name: Integration Test
        run: make INTEGRATION_SCOPE=saucelabs integration-test
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          SAUCE_TUNNEL_ID: github-serenity-js-test-integration-saucelabs-${{ github.run_number }}-tunnel

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-integration-saucelabs
          path: integration/webdriverio-web/target/

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: test-integration-saucelabs-coverage-reports
          path: |
            target/**/*
            package.json

  test-integration:
    name: integration (${{ matrix.module }})
    needs:
      - compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - cucumber-1
          - cucumber-2
          - cucumber-3
          - cucumber-4
          - cucumber-5
          - cucumber-6
          - cucumber-7
          - cucumber-8
          - jasmine
          - mocha
          - playwright
          - protractor
          - webdriverio
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (@integration)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP_SCOPE=@integration install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run: 7z x -aoa compiled-libs.zip

      - name: Integration Test
        run: make INTEGRATION_SCOPE=${{ matrix.module }} integration-test

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          retention-days: 3
          name: test-integration-reports-${{ matrix.module }}
          path: |
            integration/**/target/**/*
            package.json

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 1
          name: test-integration-coverage-reports-${{ matrix.module }}
          path: |
            target/**/*
            package.json

  #
  # Publish
  #

  report-coverage:
    runs-on:  ubuntu-latest
    needs:
      - test-linux-node-lts-active
      - test-integration-saucelabs
      - test-integration
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (root)
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Download code coverage reports
        uses: actions/download-artifact@v2
        with:
          path: target/coverage

      # DEBUG
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: target/coverage

      - name: Merge code coverage reports
        run: make report

      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: code-coverage
          path: ./target/coverage

      - name: Publish coverage
        continue-on-error: true
        if: github.ref == 'refs/heads/main'
        run: npm run coverage:publish
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  publish-artifacts:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - lint
      - test-linux-node-lts-active
      - test-linux-node-lts-previous
      - test-windows-node-lts-active
      - test-integration-saucelabs
      - test-integration
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-lerna
        with:
          github_token:   ${{ secrets.GITHUB_TOKEN }}
          git_user_email: ${{ secrets.RELEASE_GH_EMAIL }}
          git_username:   ${{ secrets.RELEASE_GH_USERNAME }}
          npm_token:      ${{ secrets.NPM_TOKEN }}
      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z x -aoa compiled-libs.zip
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (root)
        uses: bahmutov/npm-install@v1
        with:
          install-command: npm ci
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Publish artifacts
        run: npm run lerna:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - uses: actions/upload-artifact@v2
#        with:
#          retention-days: 3
#          name: changelog
#          path: |
#            CHANGELOG.md

  website:
    runs-on: ubuntu-latest
    needs:
      - publish-artifacts
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
#      - uses: ./.github/actions/setup-lerna
#        if: github.ref == 'refs/heads/master'
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          git_user_email: ${{ secrets.RELEASE_GH_EMAIL }}
#          git_username: ${{ secrets.RELEASE_GH_USERNAME }}
#          npm_token: ${{ secrets.NPM_TOKEN }}

      # Todo: use tsconfig paths and references instead to avoid having to depend on compiled libs
      - name: Download compiled libs
        uses: actions/download-artifact@v2
        with:
          name: compiled-libs
      - name: Decompress Libs
        run:  7z x -aoa compiled-libs.zip
#
#      - name: Download changelog
#        if: needs.publish-artifacts.result == 'success'
#        uses: actions/download-artifact@v2
#        with:
#          name: changelog

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (@documentation)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make install
        env:
          CHROMEDRIVER_FILEPATH: "/usr/bin/chromedriver"

      - name: Compile documentation plugins
        run: make COMPILE_SCOPE=@documentation compile

      - name: Build serenity-js.org website
        run: make site

      # Debug website
      - name: Compress website
        run:  7z a serenity-js-website.zip "documentation/serenity-js.org/build"
      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: website
          path: |
            serenity-js-website.zip        
        

#      - name: Publish website
#        uses: JamesIves/github-pages-deploy-action@v4.3.0
#        if: github.ref == 'refs/heads/main'
#        with:
#          BRANCH: gh-pages
#          FOLDER: documentation/serenity-js.org/build
#          CLEAN: true
