name: Verify legacy Node versions

on: [ push, pull_request ]

jobs:
  build-previous-lts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 10.x, 12.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: make clean verify
        env:
          CI: true

