name: Website

on:
  workflow_call:

#  pull_request:
#    branches: [ main ]
#    types: [ opened, synchronize ]
#    paths:
#      - '!.github/**'
#      - '!bin/**'
#      - '!examples/**'
#      - '!integration/**'
#      - '!packages/**'
#      - '!.*'
#      - '!*.yml'
#      - '!*.json'
#      - '!*.conf.js'
#      - 'documentation/**'
#      - 'package-lock.json'
#      - '*.md'
#
#  push:
#    branches: [ main ]
#    paths:
#      - '!.github/**'
#      - '!bin/**'
#      - '!examples/**'
#      - '!integration/**'
#      - '!packages/**'
#      - '!.*'
#      - '!*.yml'
#      - '!*.json'
#      - '!*.conf.js'
#      - 'documentation/**'
#      - 'package-lock.json'
#      - '*.md'

# https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
# https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
permissions:
  contents: write

jobs:

  website:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node Modules (site)
        uses: bahmutov/npm-install@v1
        with:
          install-command: make BOOTSTRAP_SCOPE=site install

      - name: Build serenity-js.org website
        run: make site

      # Debug website
      - name: Compress website
        run: 7z a serenity-js-website.zip "documentation/serenity-js.org/build"
      - uses: actions/upload-artifact@v2
        with:
          retention-days: 3
          name: website
          path: |
            serenity-js-website.zip

  #      - name: Publish website
  #        uses: JamesIves/github-pages-deploy-action@v4.3.0
  #        if: github.ref == 'refs/heads/main'
  #        with:
  #          BRANCH: gh-pages
  #          FOLDER: documentation/serenity-js.org/build
  #          CLEAN: true
